[features]
seeds = false
skip-lint = false
[programs.localnet]
acumulative_leaderboard = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[programs.devnet]
acumulative_leaderboard = "9ukqpC44ttCKHvbMtVSVJ169fFGL28eWKmDSe8v7dytP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "wallet.json"

[scripts]
init = "npx ts-mocha -p tsconfig.json -t 1000000 tests/init_leaderboard.ts"
play = "npx ts-mocha -p tsconfig.json -t 1000000 tests/play.ts"
